version: "3.6"

services:
  increaser:
    restart: always
    build:
      context: ./increaser
      dockerfile: ./Dockerfile
    volumes:
      - ./increaser:/app
    env_file:
      - .env
    ports:
      - "${API_PORT}:80"
    networks:
      - frame_rate_increase_network

  web_app:
    restart: always
    build:
      context: ./web_interface
      dockerfile: ./Dockerfile
    volumes:
      - ./web_interface:/app
    env_file:
      - .env
    depends_on:
      - increaser
    ports:
      - "${WEB_APP_PORT}:80"
    networks:
      - frame_rate_increase_network

networks:
  frame_rate_increase_network:
